### ISSUE TITLE
Doesn't seem to add anything to the context menu

### ISSUE THREAD

**Issue by Zatker** [Blagai/Anti-Semitism-Shinigami-Eyes#1]
Am I doing something wrong? Did I just happen to catch this before it was finished?  Added the extension but it doesn't seem to be adding anything to my context menu the way shinigami eyes does.

**Comment by Blagai** [comment]
It's not finished yet, still working on the basic functions. I'll actually release it as an extension once I finish working on it and it works.

**Comment by Zatker** [comment]
Ah ok cool.  I've been hoping something like this would get made for a while and well with recent events it's more needed than ever and I got excited when I found this.  Good luck.
